spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: "postgres"
    password: ${POSTGRES_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # For development: 'update' to sync schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
cors:
  allowed-origins: http://localhost:5173