spring:
  application:
    name: killinary
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

clerk:
  webhook:
    secret: ${CLERK_WEBHOOK_SECRET}