name: "Deploy App"

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - name: build frontend
        working-directory: frontend
        run: |
          npm i
          npm run build
      
      - name: upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: inject frontend
        uses: actions/download-artifact@v4
        with: 
          name: frontend-build
          path: backend/src/main/resources/static/
        
      - name: build with maven
        working-directory: backend
        run: mvn -B package --file pom.xml
      
      - name: copy app.jar
        uses: actions/upload-artifact@v4
        with:
          name: app.jar
          path: backend/target/killinary.jar
        

  
  push-docker-image:
    needs: build-backend
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: inject app.jar
        uses: actions/download-artifact@v4
        with: 
          name: app.jar
          path: backend/target/
      
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_TAG}}

  deploy-render:
    needs: push-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: trigger render deployment
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
